#!/bin/sh

workspaces() {

ws1=1
ws2=2
ws3=3
ws4=4
ws5=5
ws6=6
ws7=7

get_is_occupied() {
    var=$(bspc query -D -d .occupied --names | grep "$1");
    occupied="notoccupied"
    if [[ "$var" -eq $1 ]]; then
        occupied="occupied"
    fi

    echo $occupied
}

get_is_focused() {
    var=$(bspc query -D -d focused --names | grep "$1");
    occupied="notfocused"
    if [[ "$var" -eq $1 ]]; then
        occupied="focused"
    fi

    echo $occupied
}

# Unoccupied
workspace="workspace"

# check if Occupied
o1=$(get_is_occupied 1)
o2=$(get_is_occupied 2)
o3=$(get_is_occupied 3)
o4=$(get_is_occupied 4)
o5=$(get_is_occupied 5)
o6=$(get_is_occupied 6)

# check if Focused
f1=$(get_is_focused 1)
f2=$(get_is_focused 2)
f3=$(get_is_focused 3)
f4=$(get_is_focused 4)
f5=$(get_is_focused 5)
f6=$(get_is_focused 6)

# check if Urgent
# u1=$(bspc query -D -d .urgent --names | grep 1)
# u2=$(bspc query -D -d .urgent --names | grep 2)
# u3=$(bspc query -D -d .urgent --names | grep 3)
# u4=$(bspc query -D -d .urgent --names | grep 4)
# u5=$(bspc query -D -d .urgent --names | grep 5)

echo 	"(box	:class \"works\" :orientation \"v\"	:halign \"center\"	:valign \"start\"	 :space-evenly \"false\" :spacing \"-5\" (button :onclick \"bspc desktop -f $ws1\"	:class	\"$workspace-1 $o1 $f1\"	\"1\") (button :onclick \"bspc desktop -f $ws2\"	:class \"$workspace-2 $o2 $f2\"	 \"2\") (button :onclick \"bspc desktop -f $ws3\"	:class \"$workspace-3 $o3 $f3\" \"3\") (button :onclick \"bspc desktop -f $ws4\"	:class \"$workspace-4 $o4 $f4\"	\"4\") (button :onclick \"bspc desktop -f $ws5\"	:class \"$workspace-5 $o5 $f5\" \"5\" )  (button :onclick \"bspc desktop -f $ws6\"	:class \"$workspace-6 $o6 $f6\" \"6\"))"

}

workspaces
bspc subscribe desktop node_transfer | while read -r _ ; do
workspaces
done


